package com.example.csit228capstone.service.report;

import com.example.csit228capstone.model.report.ReportData;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Exports a {@link ReportData} to a UTF-8 CSV file.
 * No extra dependency needed — pure Java I/O.
 */
public class CSVReportExporter implements ReportExporter {

    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("MMMM dd, yyyy");

    @Override
    public void export(ReportData data, File destination) throws Exception {
        try (PrintWriter pw = new PrintWriter(
                new BufferedWriter(new FileWriter(destination)))) {

            // ── Metadata header ───────────────────────────────────────────────
            pw.println(escapeCsv(data.getTitle()));
            pw.println("Generated by:," + escapeCsv(nvl(data.getGeneratedBy())));
            pw.println("Date:," + escapeCsv(LocalDate.now().format(DATE_FMT)));

            String dateRange = buildDateRange(data.getStartDate(), data.getEndDate());
            if (!dateRange.isEmpty()) {
                pw.println("Period:," + escapeCsv(dateRange));
            }

            // Summary lines
            if (data.getSummaryLines() != null) {
                for (String line : data.getSummaryLines()) {
                    pw.println(escapeCsv(line));
                }
            }

            pw.println(); // blank separator

            // ── Column headers ────────────────────────────────────────────────
            if (data.getHeaders() != null && !data.getHeaders().isEmpty()) {
                pw.println(joinRow(data.getHeaders()));
            }

            // ── Data rows ─────────────────────────────────────────────────────
            if (data.getRows() != null) {
                for (List<String> row : data.getRows()) {
                    pw.println(joinRow(row));
                }
            }
        }
    }

    @Override
    public String getExtension() { return "csv"; }

    @Override
    public String getDescription() { return "CSV Files (*.csv)"; }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private String joinRow(List<String> cells) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < cells.size(); i++) {
            if (i > 0) sb.append(',');
            sb.append(escapeCsv(nvl(cells.get(i))));
        }
        return sb.toString();
    }

    /** Wraps in quotes if the value contains a comma, quote, or newline. */
    private String escapeCsv(String value) {
        if (value == null) return "";
        if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }

    private String buildDateRange(LocalDate start, LocalDate end) {
        if (start == null && end == null) return "";
        if (start != null && end != null)
            return start.format(DATE_FMT) + " to " + end.format(DATE_FMT);
        if (start != null) return "From " + start.format(DATE_FMT);
        return "Until " + end.format(DATE_FMT);
    }

    private String nvl(String s) { return s != null ? s : ""; }
}