package com.example.csit228capstone.service.report;

import com.example.csit228capstone.model.report.ReportData;
import com.example.csit228capstone.model.report.ReportFormData;
import org.apache.poi.xwpf.usermodel.*;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.*;

import java.io.File;
import java.io.FileOutputStream;
import java.math.BigInteger;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Word (.docx) exporter — matching the live Report Preview exactly.
 */
public class DocxReportExporter implements ReportExporter<List<List<String>>> {

    private static final String TEAL  = "1D9E75";
    private static final String DARK  = "1A2E44";
    private static final String GRAY  = "888888";
    private static final String WHITE = "FFFFFF";
    private static final String ALT   = "F4FAF8";

    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("MMMM dd, yyyy");

    @Override public String getFormatName() { return "DOCX"; }

    // ── Tabular Report Layout (Generic Data Tables) ───────────────────────────

    @Override
    public void export(ReportData<List<List<String>>> data, File dest) throws Exception {
        try (XWPFDocument doc = new XWPFDocument();
             FileOutputStream fos = new FileOutputStream(dest)) {

            setMargins(doc, 720);
            govHeader(doc);

            centeredPara(doc, data.getTitle(), 18, true, DARK);
            if (data.getReportType() != null) {
                centeredPara(doc, data.getReportType().getDisplayName(), 11, false, TEAL);
            }
            hRule(doc, TEAL);

            if (nvl(data.getGeneratedBy()).length() > 0)
                fullRow(doc, "Generated by:", data.getGeneratedBy());
            if (data.getStartDate() != null || data.getEndDate() != null)
                fullRow(doc, "Period Covered:", genericPeriod(data));

            if (data.getSummaryLines() != null && !data.getSummaryLines().isEmpty()) {
                sectionHeader(doc, "Summary");
                for (String line : data.getSummaryLines())
                    bodyPara(doc, line, 10, false, null);
            }

            if (data.getHeaders() != null && !data.getHeaders().isEmpty()) {
                sectionHeader(doc, "Data");
                List<List<String>> rows = data.getPayload() != null ? data.getPayload() : List.of();
                dataTable(doc, data.getHeaders(), rows);
            }

            blank(doc); blank(doc);
            rightPara(doc, "___________________________", 10, false, null);
            rightPara(doc, "Authorized Signatory", 9, false, GRAY);
            doc.write(fos);
        }
    }

    // ── Incident Report Layout (Form-Based Matching Preview Exactly) ──────────

    public void exportIncident(ReportData<ReportFormData> data, File dest) throws Exception {
        ReportFormData fd = data.getPayload();
        if (fd == null) fd = new ReportFormData();

        try (XWPFDocument doc = new XWPFDocument();
             FileOutputStream fos = new FileOutputStream(dest)) {

            setMargins(doc, 720);
            govHeader(doc);

            // App Dashboard Header Section
            centeredPara(doc, data.getTitle().toUpperCase(), 18, true, DARK);
            centeredPara(doc, "Incident Report", 11, false, TEAL);
            hRule(doc, TEAL);

            // ── UNIVERSAL METADATA BLOCK ──
            twoColRow(doc,
                    "Date:", fd.getDate() != null ? fd.getDate().format(DATE_FMT) : "—",
                    "Report No.:", nvl(fd.getReportNo()));

            twoColRow(doc,
                    "Reported by:", nvl(fd.getReportedBy()),
                    "Recorded by:", nvl(fd.getRecordedBy()));

            twoColRow(doc,
                    "Reporter Contact:", nvl(fd.getReporterContactInfo()),
                    "Recorder Contact:", nvl(fd.getRecorderContactInfo()));

            // Generated on Line
            if (fd.getStartDate() != null || fd.getEndDate() != null) {
                fullRow(doc, "Generated on:", periodStr(fd.getStartDate(), fd.getEndDate()));
            } else {
                fullRow(doc, "Generated on:", fd.getDate() != null ? fd.getDate().format(DATE_FMT) + " 11:47" : "—");
            }

            // ── INCIDENT DETAILS SECTION ──
            sectionHeader(doc, "Incident Details");
            twoColRow(doc,
                    "Date of Incident:", fd.getDateOfIncident() != null ? fd.getDateOfIncident().format(DATE_FMT) : "—",
                    "Location:", nvl(fd.getLocation()));

            fullRow(doc, "Description:", nvl(fd.getDescription()));

            // Render Incident Type Checkboxes cleanly
            boolean hasCheckedTypes = fd.getIncidentTypes() != null && !fd.getIncidentTypes().isEmpty();
            boolean hasOtherText = !nvl(fd.getIncidentTypeOther()).isEmpty();
            if (hasCheckedTypes || hasOtherText) {
                XWPFParagraph p = doc.createParagraph();
                p.setSpacingBefore(60);
                p.setSpacingAfter(60);
                StringBuilder sb = new StringBuilder();
                if (hasCheckedTypes) {
                    for (String t : fd.getIncidentTypes()) sb.append("☑ ").append(t).append("   ");
                }
                if (hasOtherText) {
                    sb.append("☑ Other: ").append(fd.getIncidentTypeOther());
                }
                XWPFRun r = p.createRun();
                r.setText(sb.toString().trim());
                r.setFontSize(10);
            }

            // Insurance Segment Block
            String ins = fd.getHasInsurance() == null ? "N/A" : fd.getHasInsurance() ? "Yes" : "No";
            threeColRow(doc,
                    "Insurance:", ins,
                    "Policy:", nvl(fd.getInsurancePolicy()),
                    "Coverage:", nvl(fd.getInsuranceCoverageAmt()));

            // ── PROPERTY DAMAGES TABLE ──
            sectionHeader(doc, "Property Damages");
            List<String> damageHeaders = List.of("Damage Item", "Estimated Value", "Repair Plan", "Repair Cost");

            XWPFTable damageTable = doc.createTable(1, 4);
            damageTable.setWidth("100%");
            buildTableHeader(damageTable, damageHeaders);

            if (fd.getDamages() != null && !fd.getDamages().isEmpty()) {
                int visualIndex = 1;
                for (ReportFormData.DamageRow dmg : fd.getDamages()) {
                    XWPFTableRow row = damageTable.createRow();
                    String bgColor = visualIndex % 2 == 0 ? WHITE : ALT;

                    // FIX: Direct field access to match ReportFormData.DamageRow structure
                    fillCell(row.getCell(0), nvl(dmg.damage), bgColor);
                    fillCell(row.getCell(1), nvl(dmg.value), bgColor);
                    fillCell(row.getCell(2), nvl(dmg.repairPlan), bgColor);
                    fillCell(row.getCell(3), nvl(dmg.repairCost), bgColor);
                    visualIndex++;
                }
            } else {
                appendEmptyTableRow(damageTable, 4);
            }
            doc.createParagraph().setSpacingAfter(40);

            // ── CASUALTIES / INJURIES TABLE ──
            sectionHeader(doc, "Casualties / Injuries");
            List<String> injuryHeaders = List.of("Injured Person", "Position", "Medical Cost", "Insurance");

            XWPFTable injuryTable = doc.createTable(1, 4);
            injuryTable.setWidth("100%");
            buildTableHeader(injuryTable, injuryHeaders);

            if (fd.getInjuries() != null && !fd.getInjuries().isEmpty()) {
                int visualIndex = 1;
                for (ReportFormData.InjuryRow inj : fd.getInjuries()) {
                    XWPFTableRow row = injuryTable.createRow();
                    String bgColor = visualIndex % 2 == 0 ? WHITE : ALT;

                    // FIX: Direct field access to match ReportFormData.InjuryRow structure
                    fillCell(row.getCell(0), nvl(inj.injuredPerson), bgColor);
                    fillCell(row.getCell(1), nvl(inj.position), bgColor);
                    fillCell(row.getCell(2), nvl(inj.medicalCost), bgColor);
                    fillCell(row.getCell(3), nvl(inj.insurance), bgColor);
                    visualIndex++;
                }
            } else {
                appendEmptyTableRow(injuryTable, 4);
            }

            // Bottom Signature Block Alignment
            blank(doc); blank(doc);
            rightPara(doc, "___________________________", 10, false, null);
            rightPara(doc, "Authorized Signatory", 9, false, GRAY);

            doc.write(fos);
        }
    }

    // ── POI Layout Helpers ────────────────────────────────────────────────────

    private void buildTableHeader(XWPFTable table, List<String> headers) {
        XWPFTableRow hdr = table.getRow(0);
        for (int c = 0; c < headers.size(); c++) {
            XWPFTableCell cl = hdr.getCell(c);
            if (cl == null) cl = hdr.createCell();
            bg(cl, TEAL);
            XWPFParagraph p = cl.getParagraphs().get(0);
            XWPFRun r = p.createRun();
            r.setText(headers.get(c)); r.setBold(true); r.setFontSize(10); r.setColor(WHITE);
        }
    }

    private void fillCell(XWPFTableCell cell, String text, String bgColor) {
        bg(cell, bgColor);
        XWPFParagraph p = cell.getParagraphs().get(0);
        XWPFRun r = p.createRun();
        r.setText(text.isEmpty() ? "—" : text);
        r.setFontSize(9);
    }

    private void appendEmptyTableRow(XWPFTable table, int colCount) {
        XWPFTableRow row = table.createRow();
        for (int i = 0; i < colCount; i++) {
            fillCell(row.getCell(i), "—", WHITE);
        }
    }

    private void setMargins(XWPFDocument doc, long twips) {
        CTBody b = doc.getDocument().getBody();
        CTSectPr sect = b.isSetSectPr() ? b.getSectPr() : b.addNewSectPr();
        CTPageMar m = sect.isSetPgMar() ? sect.getPgMar() : sect.addNewPgMar();
        BigInteger v = BigInteger.valueOf(twips);
        m.setTop(v); m.setBottom(v); m.setLeft(v); m.setRight(v);
    }

    private void govHeader(XWPFDocument doc) {
        centeredPara(doc, "Republic of the Philippines", 9, false, GRAY);
        centeredPara(doc, "Barangay Management System — LIGTAS", 9, false, GRAY);
    }

    private void centeredPara(XWPFDocument doc, String text, int size, boolean bold, String color) {
        XWPFParagraph p = doc.createParagraph();
        p.setAlignment(ParagraphAlignment.CENTER);
        run(p, text, size, bold, color);
    }

    private void rightPara(XWPFDocument doc, String text, int size, boolean bold, String color) {
        XWPFParagraph p = doc.createParagraph();
        p.setAlignment(ParagraphAlignment.RIGHT);
        run(p, text, size, bold, color);
    }

    private void bodyPara(XWPFDocument doc, String text, int size, boolean bold, String color) {
        run(doc.createParagraph(), text, size, bold, color);
    }

    private void blank(XWPFDocument doc) { doc.createParagraph(); }

    private void run(XWPFParagraph p, String text, int size, boolean bold, String color) {
        XWPFRun r = p.createRun();
        r.setText(text); r.setFontSize(size); r.setBold(bold);
        if (color != null) r.setColor(color);
    }

    private void hRule(XWPFDocument doc, String color) {
        XWPFParagraph p = doc.createParagraph();
        p.getCTP().addNewPPr().addNewRPr();
        CTBorder b = p.getCTP().getPPr().addNewPBdr().addNewBottom();
        b.setVal(STBorder.SINGLE); b.setSz(BigInteger.valueOf(6)); b.setColor(color);
    }

    private void sectionHeader(XWPFDocument doc, String title) {
        doc.createParagraph().setSpacingAfter(40);
        XWPFParagraph p = doc.createParagraph();
        p.setSpacingBefore(120);
        XWPFRun r = p.createRun();
        r.setText(title); r.setFontSize(11); r.setBold(true); r.setColor(TEAL);
    }

    private void twoColRow(XWPFDocument doc, String l1, String v1, String l2, String v2) {
        XWPFTable t = doc.createTable(1, 4);
        t.setWidth("100%"); noBorders(t);
        cell(t, 0, 0, l1, true, null, false);
        cell(t, 0, 1, v1, false, null, true);
        cell(t, 0, 2, l2, true, null, false);
        cell(t, 0, 3, v2, false, null, true);
        doc.createParagraph().setSpacingAfter(20);
    }

    private void fullRow(XWPFDocument doc, String label, String value) {
        XWPFTable t = doc.createTable(1, 2);
        t.setWidth("100%"); noBorders(t);
        t.getRow(0).getCell(0).getCTTc().addNewTcPr().addNewTcW().setW(BigInteger.valueOf(1800));
        cell(t, 0, 0, label, true, null, false);
        cell(t, 0, 1, value, false, null, true);
        doc.createParagraph().setSpacingAfter(20);
    }

    private void threeColRow(XWPFDocument doc, String l1, String v1, String l2, String v2, String l3, String v3) {
        XWPFTable t = doc.createTable(1, 6);
        t.setWidth("100%"); noBorders(t);
        cell(t, 0, 0, l1, true, null, false);
        cell(t, 0, 1, v1, false, null, true);
        cell(t, 0, 2, l2, true, null, false);
        cell(t, 0, 3, v2, false, null, true);
        cell(t, 0, 4, l3, true, null, false);
        cell(t, 0, 5, v3, false, null, true);
        doc.createParagraph().setSpacingAfter(20);
    }

    private void dataTable(XWPFDocument doc, List<String> headers, List<List<String>> rows) {
        int cols = headers.size();
        XWPFTable t = doc.createTable(Math.max(1, rows.size() + 1), cols);
        t.setWidth("100%");
        buildTableHeader(t, headers);

        int visualIndex = 1;
        for (int ri = 0; ri < rows.size(); ri++) {
            List<String> row = rows.get(ri);
            boolean isRowBlank = row.stream().allMatch(text -> text == null || text.trim().isBlank() || "-".equals(text.trim()));
            if (isRowBlank) continue;

            XWPFTableRow tr = t.getRow(visualIndex);
            if (tr == null) tr = t.createRow();
            String bgColor = visualIndex % 2 == 0 ? WHITE : ALT;

            for (int c = 0; c < cols; c++) {
                fillCell(tr.getCell(c), c < row.size() ? nvl(row.get(c)) : "—", bgColor);
            }
            visualIndex++;
        }
        doc.createParagraph().setSpacingAfter(40);
    }

    private void cell(XWPFTable t, int row, int col, String text, boolean bold, String color, boolean bottomBorder) {
        XWPFTableRow rRow = t.getRow(row);
        XWPFTableCell c = rRow.getCell(col);
        if (c == null) {
            for (int i = rRow.getTableCells().size(); i <= col; i++) rRow.createCell();
            c = rRow.getCell(col);
        }
        XWPFParagraph p = c.getParagraphs().get(0);
        for (int i = p.getRuns().size() - 1; i >= 0; i--) p.removeRun(i);

        XWPFRun r = p.createRun();
        r.setText(nvl(text).isEmpty() ? "—" : text);
        r.setBold(bold);
        r.setFontSize(10);
        if (color != null) r.setColor(color);

        if (bottomBorder) {
            CTTcPr cellProps = c.getCTTc().isSetTcPr() ? c.getCTTc().getTcPr() : c.getCTTc().addNewTcPr();
            CTTcBorders cellBorders = cellProps.isSetTcBorders() ? cellProps.getTcBorders() : cellProps.addNewTcBorders();
            CTBorder bottom = cellBorders.addNewBottom();
            bottom.setVal(STBorder.SINGLE);
            bottom.setSz(BigInteger.valueOf(4));
            bottom.setColor("D3D3D3");
        }
    }

    private void bg(XWPFTableCell c, String hex) {
        CTShd sh = c.getCTTc().addNewTcPr().addNewShd();
        sh.setFill(hex); sh.setVal(STShd.CLEAR);
    }

    private void noBorders(XWPFTable t) {
        CTTblPr pr = t.getCTTbl().getTblPr() != null ? t.getCTTbl().getTblPr() : t.getCTTbl().addNewTblPr();
        CTTblBorders b = pr.isSetTblBorders() ? pr.getTblBorders() : pr.addNewTblBorders();
        b.addNewTop().setVal(STBorder.NONE);     b.addNewBottom().setVal(STBorder.NONE);
        b.addNewLeft().setVal(STBorder.NONE);    b.addNewRight().setVal(STBorder.NONE);
        b.addNewInsideH().setVal(STBorder.NONE); b.addNewInsideV().setVal(STBorder.NONE);
    }

    private String genericPeriod(ReportData<List<List<String>>> d) {
        return periodStr(d.getStartDate(), d.getEndDate());
    }

    private String periodStr(java.time.LocalDate start, java.time.LocalDate end) {
        String s = start != null ? start.format(DATE_FMT) : "";
        String e = end != null ? end.format(DATE_FMT) : "";
        return s.isEmpty() ? e : e.isEmpty() ? s : s + " — " + e;
    }

    private String nvl(String s) { return s != null ? s : ""; }
}