package com.example.csit228capstone.service.report;

import com.example.csit228capstone.model.report.ReportData;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.*;

import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Exports a {@link ReportData} to a styled .xlsx file using Apache POI.
 *
 * Requires in pom.xml (add if not present):
 * <dependency>
 *   <groupId>org.apache.poi</groupId>
 *   <artifactId>poi-ooxml</artifactId>
 *   <version>5.2.5</version>
 * </dependency>
 */
public class ExcelReportExporter implements ReportExporter {

    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("MMMM dd, yyyy");

    @Override
    public void export(ReportData data, File destination) throws Exception {
        try (XSSFWorkbook wb = new XSSFWorkbook();
             FileOutputStream fos = new FileOutputStream(destination)) {

            XSSFSheet sheet = wb.createSheet(
                    data.getReportType() != null ? data.getReportType().getDisplayName() : "Report");

            // ── Styles ───────────────────────────────────────────────────────
            CellStyle titleStyle = wb.createCellStyle();
            XSSFFont titleFont = wb.createFont();
            titleFont.setBold(true);
            titleFont.setFontHeightInPoints((short) 16);
            titleStyle.setFont(titleFont);
            titleStyle.setAlignment(HorizontalAlignment.CENTER);

            CellStyle metaStyle = wb.createCellStyle();
            XSSFFont metaFont = wb.createFont();
            metaFont.setColor(IndexedColors.GREY_50_PERCENT.getIndex());
            metaFont.setFontHeightInPoints((short) 9);
            metaStyle.setFont(metaFont);
            metaStyle.setAlignment(HorizontalAlignment.CENTER);

            CellStyle summaryStyle = wb.createCellStyle();
            XSSFFont summaryFont = wb.createFont();
            summaryFont.setBold(true);
            summaryFont.setFontHeightInPoints((short) 10);
            summaryStyle.setFont(summaryFont);
            summaryStyle.setAlignment(HorizontalAlignment.CENTER);

            // Teal header style
            CellStyle headerStyle = wb.createCellStyle();
            XSSFFont headerFont = wb.createFont();
            headerFont.setBold(true);
            headerFont.setColor(IndexedColors.WHITE.getIndex());
            headerFont.setFontHeightInPoints((short) 10);
            headerStyle.setFont(headerFont);
            headerStyle.setFillForegroundColor(new XSSFColor(new byte[]{0x1D, (byte)0x9E, 0x75}, null));
            headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            headerStyle.setAlignment(HorizontalAlignment.CENTER);
            setBorder(headerStyle);

            // Alternating row styles
            CellStyle rowStyle = wb.createCellStyle();
            rowStyle.setWrapText(true);
            setBorder(rowStyle);

            CellStyle altRowStyle = wb.createCellStyle();
            altRowStyle.setFillForegroundColor(new XSSFColor(new byte[]{(byte)0xF0, (byte)0xF9, (byte)0xF5}, null));
            altRowStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            altRowStyle.setWrapText(true);
            setBorder(altRowStyle);

            // ── Title rows ───────────────────────────────────────────────────
            int currentRow = 0;
            int colCount = data.getHeaders() != null ? data.getHeaders().size() : 1;

            Row titleRow = sheet.createRow(currentRow++);
            titleRow.setHeightInPoints(24);
            Cell titleCell = titleRow.createCell(0);
            titleCell.setCellValue(data.getTitle());
            titleCell.setCellStyle(titleStyle);
            if (colCount > 1) sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, colCount - 1));

            // Metadata
            String dateRange = buildDateRange(data.getStartDate(), data.getEndDate());
            String metaText = "Generated by: " + nvl(data.getGeneratedBy())
                    + "   |   Date: " + LocalDate.now().format(DATE_FMT)
                    + (dateRange.isEmpty() ? "" : "   |   Period: " + dateRange);
            Row metaRow = sheet.createRow(currentRow++);
            Cell metaCell = metaRow.createCell(0);
            metaCell.setCellValue(metaText);
            metaCell.setCellStyle(metaStyle);
            if (colCount > 1) sheet.addMergedRegion(new CellRangeAddress(1, 1, 0, colCount - 1));

            // Summary lines
            if (data.getSummaryLines() != null && !data.getSummaryLines().isEmpty()) {
                Row summaryRow = sheet.createRow(currentRow++);
                Cell summaryCell = summaryRow.createCell(0);
                summaryCell.setCellValue(String.join("   |   ", data.getSummaryLines()));
                summaryCell.setCellStyle(summaryStyle);
                if (colCount > 1)
                    sheet.addMergedRegion(new CellRangeAddress(currentRow - 1, currentRow - 1, 0, colCount - 1));
            }

            currentRow++; // blank row spacer

            // ── Header row ───────────────────────────────────────────────────
            if (data.getHeaders() != null && !data.getHeaders().isEmpty()) {
                Row headerRow = sheet.createRow(currentRow++);
                headerRow.setHeightInPoints(18);
                List<String> headers = data.getHeaders();
                for (int c = 0; c < headers.size(); c++) {
                    Cell cell = headerRow.createCell(c);
                    cell.setCellValue(headers.get(c));
                    cell.setCellStyle(headerStyle);
                }

                // ── Data rows ─────────────────────────────────────────────────
                List<List<String>> rows = data.getRows();
                if (rows != null) {
                    for (int r = 0; r < rows.size(); r++) {
                        Row dataRow = sheet.createRow(currentRow++);
                        List<String> rowValues = rows.get(r);
                        CellStyle style = (r % 2 == 1) ? altRowStyle : rowStyle;
                        for (int c = 0; c < rowValues.size(); c++) {
                            Cell cell = dataRow.createCell(c);
                            cell.setCellValue(nvl(rowValues.get(c)));
                            cell.setCellStyle(style);
                        }
                    }
                }

                // Auto-size columns
                for (int c = 0; c < headers.size(); c++) {
                    sheet.autoSizeColumn(c);
                    // Cap max width
                    if (sheet.getColumnWidth(c) > 12000) sheet.setColumnWidth(c, 12000);
                }
            }

            wb.write(fos);
        }
    }

    @Override
    public String getExtension() { return "xlsx"; }

    @Override
    public String getDescription() { return "Excel Files (*.xlsx)"; }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private void setBorder(CellStyle style) {
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
    }

    private String buildDateRange(LocalDate start, LocalDate end) {
        if (start == null && end == null) return "";
        if (start != null && end != null)
            return start.format(DATE_FMT) + " – " + end.format(DATE_FMT);
        if (start != null) return "From " + start.format(DATE_FMT);
        return "Until " + end.format(DATE_FMT);
    }

    private String nvl(String s) { return s != null ? s : ""; }
}