package com.example.csit228capstone.service.report;

import com.example.csit228capstone.model.report.ReportData;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Exports a {@link ReportData} to a formatted PDF file using iText 7/8.
 * iText is already on the classpath (itext7-core 8.0.3 in pom.xml).
 */
public class PDFReportExporter implements ReportExporter {

    private static final DeviceRgb HEADER_BG  = new DeviceRgb(0x1D, 0x9E, 0x75); // teal
    private static final DeviceRgb ALT_ROW_BG = new DeviceRgb(0xF0, 0xF9, 0xF5);
    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("MMMM dd, yyyy");

    @Override
    public void export(ReportData data, File destination) throws Exception {
        try (PdfDocument pdf = new PdfDocument(new PdfWriter(destination));
             Document doc = new Document(pdf, PageSize.A4.rotate())) {

            doc.setMargins(36, 36, 36, 36);

            // ── Title block ──────────────────────────────────────────────────
            doc.add(new Paragraph("Republic of the Philippines\nBarangay Management System")
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontSize(10)
                    .setFontColor(ColorConstants.DARK_GRAY));

            doc.add(new Paragraph(data.getTitle())
                    .setTextAlignment(TextAlignment.CENTER)
                    .setBold()
                    .setFontSize(18)
                    .setMarginTop(4));

            // ── Metadata line ────────────────────────────────────────────────
            String dateRange = buildDateRange(data.getStartDate(), data.getEndDate());
            doc.add(new Paragraph(
                    "Generated by: " + nvl(data.getGeneratedBy()) +
                            "   |   Date: " + LocalDate.now().format(DATE_FMT) +
                            (dateRange.isEmpty() ? "" : "   |   Period: " + dateRange))
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontSize(9)
                    .setFontColor(ColorConstants.GRAY)
                    .setMarginBottom(8));

            // ── Summary lines ────────────────────────────────────────────────
            if (data.getSummaryLines() != null && !data.getSummaryLines().isEmpty()) {
                String summary = String.join("   |   ", data.getSummaryLines());
                doc.add(new Paragraph(summary)
                        .setTextAlignment(TextAlignment.CENTER)
                        .setFontSize(10)
                        .setBold()
                        .setMarginBottom(12));
            }

            // ── Data table ───────────────────────────────────────────────────
            List<String> headers = data.getHeaders();
            if (headers != null && !headers.isEmpty()) {
                float[] widths = new float[headers.size()];
                for (int i = 0; i < widths.length; i++) {
                    widths[i] = i == 0 ? 1 : 3; // give first column (usually #) less width
                }

                Table table = new Table(UnitValue.createPercentArray(widths))
                        .useAllAvailableWidth();

                // Header row
                for (String h : headers) {
                    table.addHeaderCell(new Cell()
                            .setBackgroundColor(HEADER_BG)
                            .setFontColor(ColorConstants.WHITE)
                            .setBold()
                            .setFontSize(9)
                            .setPadding(5)
                            .add(new Paragraph(h)));
                }

                // Data rows
                List<List<String>> rows = data.getRows();
                if (rows != null) {
                    for (int r = 0; r < rows.size(); r++) {
                        List<String> row = rows.get(r);
                        boolean alt = (r % 2 == 1);
                        for (String cell : row) {
                            Cell tableCell = new Cell()
                                    .setFontSize(8)
                                    .setPadding(4)
                                    .add(new Paragraph(nvl(cell)));
                            if (alt) tableCell.setBackgroundColor(ALT_ROW_BG);
                            table.addCell(tableCell);
                        }
                    }
                }

                doc.add(table);
            }

            // ── Footer ───────────────────────────────────────────────────────
            doc.add(new Paragraph("\n\n___________________________\nAuthorized Signatory")
                    .setTextAlignment(TextAlignment.RIGHT)
                    .setFontSize(9)
                    .setMarginTop(24));
        }
    }

    @Override
    public String getExtension() { return "pdf"; }

    @Override
    public String getDescription() { return "PDF Files (*.pdf)"; }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private String buildDateRange(LocalDate start, LocalDate end) {
        if (start == null && end == null) return "";
        if (start != null && end != null)
            return start.format(DATE_FMT) + " – " + end.format(DATE_FMT);
        if (start != null) return "From " + start.format(DATE_FMT);
        return "Until " + end.format(DATE_FMT);
    }

    private String nvl(String s) {
        return s != null ? s : "";
    }
}