package com.example.csit228capstone.service.report;

import com.example.csit228capstone.model.report.ReportData;
import com.example.csit228capstone.model.report.ReportFormData;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.Color;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.draw.SolidLine;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

import java.io.File;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * PDF Exporter — Production ready edition matching user preview layout.
 */
public class PDFReportExporter implements ReportExporter<List<List<String>>> {

    private static final Color TEAL     = new DeviceRgb(0x1D, 0x9E, 0x75);
    private static final Color TEAL_ALT = new DeviceRgb(0xF4, 0xFA, 0xF8);
    private static final Color DARK     = new DeviceRgb(0x1A, 0x2E, 0x44);
    private static final Color GRAY     = new DeviceRgb(0x88, 0x88, 0x88);

    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("MMMM dd, yyyy");

    @Override public String getFormatName() { return "PDF"; }

    // ── Tabular Report Layout ─────────────────────────────────────────────────

    @Override
    public void export(ReportData<List<List<String>>> data, File dest) throws Exception {
        try (PdfDocument pdf = new PdfDocument(new PdfWriter(dest));
             Document doc    = new Document(pdf, PageSize.A4)) {

            doc.setMargins(40, 40, 40, 40);
            govHeader(doc);

            doc.add(para(data.getTitle(), 18, true, DARK).setTextAlignment(TextAlignment.CENTER).setMarginTop(4));
            if (data.getReportType() != null)
                doc.add(para(data.getReportType().getDisplayName(), 11, false, TEAL).setTextAlignment(TextAlignment.CENTER));

            doc.add(new LineSeparator(new SolidLine(0.5f)).setMarginBottom(6));

            if (nvl(data.getGeneratedBy()).length() > 0)
                doc.add(fullRow("Generated by:", data.getGeneratedBy()));
            if (data.getStartDate() != null || data.getEndDate() != null)
                doc.add(fullRow("Period Covered:", genericPeriod(data)));

            if (data.getSummaryLines() != null && !data.getSummaryLines().isEmpty()) {
                sectionHeader(doc, "Summary");
                for (String line : data.getSummaryLines())
                    doc.add(para(line, 10, false, null).setMarginLeft(8));
            }

            if (data.getHeaders() != null && !data.getHeaders().isEmpty()) {
                sectionHeader(doc, "Data");
                List<List<String>> rows = data.getPayload() != null ? data.getPayload() : List.of();
                doc.add(dataTable(data.getHeaders(), rows));
            }

            signature(doc, "___________________________");
        }
    }

    // ── Incident Report Layout (Form-Based Matching Preview) ──────────────────

    public void exportIncident(ReportData<ReportFormData> data, File dest) throws Exception {
        ReportFormData fd = data.getPayload();
        if (fd == null) fd = new ReportFormData();

        try (PdfDocument pdf = new PdfDocument(new PdfWriter(dest));
             Document doc    = new Document(pdf, PageSize.A4)) {

            doc.setMargins(40, 40, 40, 40);
            govHeader(doc);

            doc.add(para(data.getTitle().toUpperCase(), 18, true, DARK).setTextAlignment(TextAlignment.CENTER).setMarginTop(4));
            doc.add(para("Incident Report", 11, false, TEAL).setTextAlignment(TextAlignment.CENTER));
            doc.add(new LineSeparator(new SolidLine(0.5f)).setMarginBottom(6));

            doc.add(twoColRow("Date:", fd.getDate() != null ? fd.getDate().format(DATE_FMT) : "—", "Report No.:", nvl(fd.getReportNo())));
            doc.add(twoColRow("Reported by:", nvl(fd.getReportedBy()), "Recorded by:", nvl(fd.getRecordedBy())));
            doc.add(twoColRow("Reporter Contact:", nvl(fd.getReporterContactInfo()), "Recorder Contact:", nvl(fd.getRecorderContactInfo())));

            // FIX: Reference properties directly to clear compilation errors
            if (data.getStartDate() != null || data.getEndDate() != null) {
                doc.add(fullRow("Generated on:", periodStr(data.getStartDate(), data.getEndDate())));
            } else {
                doc.add(fullRow("Generated on:", fd.getDate() != null ? fd.getDate().format(DATE_FMT) + " 11:47" : "—"));
            }

            sectionHeader(doc, "Incident Details");
            doc.add(twoColRow("Date of Incident:", fd.getDateOfIncident() != null ? fd.getDateOfIncident().format(DATE_FMT) : "—", "Location:", nvl(fd.getLocation())));
            doc.add(fullRow("Description:", nvl(fd.getDescription())));

            boolean hasCheckedTypes = fd.getIncidentTypes() != null && !fd.getIncidentTypes().isEmpty();
            boolean hasOtherText = !nvl(fd.getIncidentTypeOther()).isEmpty();

            if (hasCheckedTypes || hasOtherText) {
                StringBuilder sb = new StringBuilder();
                if (hasCheckedTypes) {
                    for (String t : fd.getIncidentTypes()) sb.append("☑ ").append(t).append("   ");
                }
                if (hasOtherText) {
                    sb.append("☑ Other: ").append(fd.getIncidentTypeOther());
                }
                doc.add(para(sb.toString().trim(), 10, false, null).setMarginTop(4).setMarginBottom(4));
            }

            String ins = fd.getHasInsurance() == null ? "N/A" : fd.getHasInsurance() ? "Yes" : "No";
            Table insRow = new Table(UnitValue.createPercentArray(new float[]{1.5f, 2.1f, 1.0f, 2.1f, 1.0f, 2.1f})).useAllAvailableWidth().setMarginBottom(4);
            insRow.addCell(lc("Insurance?")); insRow.addCell(vc(ins));
            insRow.addCell(lc("Policy:"));    insRow.addCell(vc(nvl(fd.getInsurancePolicy())));
            insRow.addCell(lc("Coverage:"));  insRow.addCell(vc(nvl(fd.getInsuranceCoverageAmt())));
            doc.add(insRow);

            sectionHeader(doc, "Property Damages");
            doc.add(dataTable(
                    List.of("Damage Item", "Estimated Value", "Repair Plan", "Repair Cost"),
                    fd.getDamages() == null ? List.of() :
                            fd.getDamages().stream()
                                    .map(r -> List.of(nvl(r.damage), nvl(r.value), nvl(r.repairPlan), nvl(r.repairCost)))
                                    .toList()));

            sectionHeader(doc, "Casualties / Injuries");
            doc.add(dataTable(
                    List.of("Injured Person", "Position", "Medical Cost", "Insurance"),
                    fd.getInjuries() == null ? List.of() :
                            fd.getInjuries().stream()
                                    .map(r -> List.of(nvl(r.injuredPerson), nvl(r.position), nvl(r.medicalCost), nvl(r.insurance)))
                                    .toList()));

            String sigName = (!nvl(fd.getRecordedBy()).isBlank()) ? fd.getRecordedBy() : fd.getReportedBy();
            if (nvl(sigName).isBlank()) sigName = "___________________________";
            signature(doc, sigName);
        }
    }

    // ── iText Helpers ─────────────────────────────────────────────────────────

    private void govHeader(Document doc) {
        doc.add(para("Republic of the Philippines", 9, false, GRAY).setTextAlignment(TextAlignment.CENTER));
        doc.add(para("Barangay Management System — LIGTAS", 9, false, GRAY).setTextAlignment(TextAlignment.CENTER));
    }

    private Paragraph para(String text, float size, boolean bold, Color color) {
        Paragraph p = new Paragraph(text).setFontSize(size);
        if (bold) p.setBold();
        if (color != null) p.setFontColor(color);
        return p;
    }

    private void sectionHeader(Document doc, String title) {
        doc.add(new Paragraph(title)
                .setFontSize(12).setBold().setFontColor(TEAL)
                .setBorderBottom(new SolidBorder(TEAL, 0.5f))
                .setMarginTop(10).setMarginBottom(4));
    }

    private Table twoColRow(String l1, String v1, String l2, String v2) {
        Table t = new Table(UnitValue.createPercentArray(new float[]{1.8f, 2.2f, 1.8f, 2.2f})).useAllAvailableWidth().setMarginBottom(2);
        t.addCell(lc(l1)); t.addCell(vc(v1));
        t.addCell(lc(l2)); t.addCell(vc(v2));
        return t;
    }

    private Table fullRow(String label, String value) {
        Table t = new Table(UnitValue.createPercentArray(new float[]{1.8f, 6.2f})).useAllAvailableWidth().setMarginBottom(2);
        t.addCell(lc(label)); t.addCell(vc(value));
        return t;
    }

    private Cell lc(String text) {
        return new Cell().add(para(text, 9, true, null)).setBorder(Border.NO_BORDER).setPadding(2);
    }

    private Cell vc(String text) {
        return new Cell().add(para(nvl(text).isEmpty() ? "—" : text, 9, false, null))
                .setBorder(Border.NO_BORDER).setBorderBottom(new SolidBorder(ColorConstants.LIGHT_GRAY, 0.5f)).setPadding(2);
    }

    private Table dataTable(List<String> headers, List<List<String>> rows) {
        float[] w = new float[headers.size()];
        if (headers.size() == 8) {
            w = new float[]{0.4f, 1.5f, 0.5f, 0.5f, 1.0f, 2.2f, 1.2f, 1.3f};
        } else {
            for (int i = 0; i < w.length; i++) w[i] = 1.0f;
        }

        Table t = new Table(UnitValue.createPercentArray(w)).useAllAvailableWidth();
        for (String h : headers) {
            t.addHeaderCell(new Cell().add(para(h, 9, true, ColorConstants.WHITE))
                    .setBackgroundColor(TEAL).setPadding(4).setBorder(Border.NO_BORDER));
        }

        int visualIndex = 1;
        for (List<String> row : rows) {
            boolean isRowBlank = row.stream().allMatch(text -> text == null || text.trim().isBlank() || "-".equals(text.trim()));
            if (isRowBlank) continue;

            for (int c = 0; c < headers.size(); c++) {
                String v = c < row.size() ? nvl(row.get(c)) : "";
                Cell cell = new Cell().add(para(v, 8.5f, false, null)).setPadding(4)
                        .setBorder(new SolidBorder(ColorConstants.LIGHT_GRAY, 0.3f));
                if (visualIndex % 2 == 0) cell.setBackgroundColor(TEAL_ALT);
                t.addCell(cell);
            }
            visualIndex++;
        }
        return t;
    }

    private void signature(Document doc, String name) {
        doc.add(para("\n\n\n" + name + "\nAuthorized Signatory", 9, false, GRAY).setTextAlignment(TextAlignment.RIGHT).setMarginTop(20));
    }

    private String genericPeriod(ReportData<List<List<String>>> d) {
        return periodStr(d.getStartDate(), d.getEndDate());
    }

    private String periodStr(java.time.LocalDate start, java.time.LocalDate end) {
        String s = start != null ? start.format(DATE_FMT) : "";
        String e = end != null ? end.format(DATE_FMT) : "";
        return s.isEmpty() ? e : e.isEmpty() ? s : s + " — " + e;
    }

    private String nvl(String s) { return s != null ? s : ""; }
}