package com.example.csit228capstone.controller.reports;

import com.example.csit228capstone.model.report.Report;
import com.example.csit228capstone.service.ReportService;
import com.example.csit228capstone.service.report.ReportExporter;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.HBox;
import javafx.stage.FileChooser;
import javafx.stage.Modality;
import javafx.stage.Stage;

import java.io.File;
import java.io.IOException;
import java.util.List;

public class ReportsController {

    // ── FXML fields ───────────────────────────────────────────────────────────
    @FXML private Button    btnDownload;
    @FXML private Button    btnExportCsv;      // NEW: Export to CSV button
    @FXML private CheckBox  selectAllHeader;
    @FXML private TextField tfSearch;
    @FXML private ComboBox<String> filterAscOrDesc;  // kept (filterType removed per requirement)

    @FXML private TableView<Report>            reportsTable;
    @FXML private TableColumn<Report, Boolean> colSelect;
    @FXML private TableColumn<Report, String>  colName;
    @FXML private TableColumn<Report, String>  colType;
    @FXML private TableColumn<Report, String>  colGeneratedDateTime;
    @FXML private TableColumn<Report, String>  colGeneratedBy;
    @FXML private TableColumn<Report, Void>    colActions;

    // ── State ─────────────────────────────────────────────────────────────────
    private final ObservableList<Report> reportData = FXCollections.observableArrayList();
    private final ReportService          service    = new ReportService();

    /** Sort-field options shown in the ComboBox (display label → DB column). */
    private static final String[] SORT_LABELS = {
            "Date Generated (Newest)",
            "Date Generated (Oldest)",
            "Report Name (A-Z)",
            "Report Name (Z-A)",
            "Generated By (A-Z)",
            "Generated By (Z-A)"
    };

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    @FXML
    public void initialize() {
        try {
            setUpTable();
            setUpFilter();
        } catch (Exception e) {
            e.printStackTrace(); // LOOK AT YOUR IDE CONSOLE FOR THE OUTPUT
        }
    }

    // ── Setup ─────────────────────────────────────────────────────────────────

    private void setUpTable() {
        setupSelectColumn();
        colName.setCellValueFactory(new PropertyValueFactory<>("name"));
        colType.setCellValueFactory(new PropertyValueFactory<>("type"));
        colGeneratedDateTime.setCellValueFactory(new PropertyValueFactory<>("formattedDate"));
        colGeneratedBy.setCellValueFactory(new PropertyValueFactory<>("generatedBy"));
        setupActionColumn();
        reportsTable.setItems(reportData);
    }

    private void setUpFilter() {
        filterAscOrDesc.setItems(FXCollections.observableArrayList(SORT_LABELS));
        filterAscOrDesc.setValue(SORT_LABELS[0]);

        // React to sort change
        filterAscOrDesc.setOnAction(e -> loadReports());

        // React to search text change (live filter)
        tfSearch.textProperty().addListener((obs, oldVal, newVal) -> loadReports());
        loadReports();
    }

    private void setupSelectColumn() {
        colSelect.setCellValueFactory(new PropertyValueFactory<>("selected"));
        colSelect.setCellFactory(column -> new TableCell<>() {
            private final CheckBox checkBox = new CheckBox();
            {
                checkBox.setOnAction(event -> {
                    Report report = getTableView().getItems().get(getIndex());
                    report.setSelected(checkBox.isSelected());
                    updateToolbarButtons();
                });
            }

            @Override
            protected void updateItem(Boolean item, boolean empty) {
                super.updateItem(item, empty);
                if (empty) {
                    setGraphic(null);
                } else {
                    Report report = getTableView().getItems().get(getIndex());
                    checkBox.setSelected(report.isSelected());
                    setGraphic(checkBox);
                    setStyle("-fx-alignment: CENTER;");
                }
            }
        });
    }

    private void setupActionColumn() {
        colActions.setCellFactory(param -> new TableCell<>() {
            private final Button btnView   = new Button("View");
            private final Button btnDelete = new Button("Delete");
            private final HBox   container = new HBox(8, btnView, btnDelete);

            {
                btnView.setStyle("""
                    -fx-background-color: #b6d0e2;
                    -fx-text-fill: #1a4599;
                    -fx-font-size: 10px;
                    -fx-padding: 3 8 3 8;
                    -fx-background-radius: 4;
                    -fx-cursor: hand;
                    """);
                btnDelete.setStyle("""
                    -fx-background-color: #fecaca;
                    -fx-text-fill: #991b1b;
                    -fx-font-size: 10px;
                    -fx-padding: 3 8 3 8;
                    -fx-background-radius: 4;
                    -fx-cursor: hand;
                    """);
                container.setStyle("-fx-alignment: CENTER;");

                btnView.setOnAction(event -> {
                    Report r = getTableView().getItems().get(getIndex());
                    if (r != null) openPreview(r);
                });
                btnDelete.setOnAction(event -> {
                    Report r = getTableView().getItems().get(getIndex());
                    handleDeleteReport(r);
                });
            }

            @Override
            protected void updateItem(Void item, boolean empty) {
                super.updateItem(item, empty);
                setGraphic(empty ? null : container);
            }
        });
    }

    // ── Data loading ──────────────────────────────────────────────────────────

    public void loadReports() {
        try {
            String search    = tfSearch.getText();
            String sortLabel = filterAscOrDesc.getValue();
            String sortField = resolveSortField(sortLabel);
            boolean asc      = isAscending(sortLabel);

            List<Report> reports = service.findAllFiltered(search, sortField, asc);
            reportData.setAll(reports);
            reportsTable.refresh();
            updateToolbarButtons();
        } catch (Exception e) {
            showAlert(Alert.AlertType.ERROR, "Database Error", "Failed to load reports: " + e.getMessage());
        }
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    @FXML
    public void generateReport(ActionEvent event) {
        try {
            FXMLLoader loader = new FXMLLoader(
                    getClass().getResource("/com/example/csit228capstone/report/ReportForm.fxml"));
            Parent root = loader.load();
            ReportFormController controller = loader.getController();
            controller.setParentController(this);

            Stage stage = new Stage();
            stage.setTitle("Generate New Report");
            stage.initModality(Modality.APPLICATION_MODAL);
            stage.setScene(new Scene(root));
            stage.show();
        } catch (IOException e) {
            e.printStackTrace();
            showAlert(Alert.AlertType.ERROR, "Navigation Error", "Could not load report form.");
        }
    }

    /** Download selected reports — opens a format chooser dialog. */
    @FXML
    public void downloadReports(ActionEvent event) {
        List<Report> selected = reportData.stream()
                .filter(Report::isSelected)
                .toList();

        if (selected.isEmpty()) {
            showAlert(Alert.AlertType.WARNING, "Nothing Selected",
                    "Please check at least one report to download.");
            return;
        }

        // Ask the user which format
        ChoiceDialog<String> dialog = new ChoiceDialog<>("pdf",
                service.getSupportedFormats());
        dialog.setTitle("Choose Export Format");
        dialog.setHeaderText("Download " + selected.size() + " report(s)");
        dialog.setContentText("Select format:");
        String format = dialog.showAndWait().orElse(null);
        if (format == null) return;

        ReportExporter exporter = service.getExporters().get(format);
        int successCount = 0;
        for (Report report : selected) {
            FileChooser chooser = new FileChooser();
            chooser.setTitle("Save \"" + report.getName() + "\"");
            chooser.setInitialFileName(sanitize(report.getName()) + "." + exporter.getExtension());
            chooser.getExtensionFilters().add(
                    new FileChooser.ExtensionFilter(exporter.getDescription(),
                            "*." + exporter.getExtension()));
            File dest = chooser.showSaveDialog(btnDownload.getScene().getWindow());
            if (dest == null) continue;

            try {
                service.export(report, format, dest);
                successCount++;
            } catch (Exception e) {
                showAlert(Alert.AlertType.ERROR, "Export Failed",
                        report.getName() + ": " + e.getMessage());
            }
        }
        if (successCount > 0) {
            showAlert(Alert.AlertType.INFORMATION, "Done",
                    successCount + " report(s) exported successfully.");
        }
    }

    /** Export ALL visible table rows directly to CSV (no format dialog). */
    @FXML
    public void exportToCsv(ActionEvent event) {
        if (reportData.isEmpty()) {
            showAlert(Alert.AlertType.WARNING, "No Data", "There are no reports to export.");
            return;
        }

        FileChooser chooser = new FileChooser();
        chooser.setTitle("Export Table to CSV");
        chooser.setInitialFileName("reports_list.csv");
        chooser.getExtensionFilters().add(
                new FileChooser.ExtensionFilter("CSV Files (*.csv)", "*.csv"));
        File dest = chooser.showSaveDialog(btnExportCsv.getScene().getWindow());
        if (dest == null) return;

        try (java.io.PrintWriter pw = new java.io.PrintWriter(dest, java.nio.charset.StandardCharsets.UTF_8)) {
            // Header
            pw.println("Report Name,Type,Generated Date & Time,Generated By");
            // Rows
            for (Report r : reportData) {
                pw.printf("%s,%s,%s,%s%n",
                        csv(r.getName()),
                        csv(r.getType()),
                        csv(r.getFormattedDate()),
                        csv(r.getGeneratedBy()));
            }
            showAlert(Alert.AlertType.INFORMATION, "CSV Exported",
                    "Report list saved to:\n" + dest.getAbsolutePath());
        } catch (Exception e) {
            showAlert(Alert.AlertType.ERROR, "Export Failed", e.getMessage());
        }
    }

    @FXML
    private void handleSelectAll(ActionEvent event) {
        boolean sel = selectAllHeader.isSelected();
        for (Report r : reportData) r.setSelected(sel);
        reportsTable.refresh();
        updateToolbarButtons();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private void openPreview(Report report) {
        try {
            FXMLLoader loader = new FXMLLoader(
                    getClass().getResource("/com/example/csit228capstone/report/ReportPreview.fxml"));
            Parent root = loader.load();
            ReportPreviewController controller = loader.getController();
            controller.loadReport(report);

            Stage stage = new Stage();
            stage.setTitle("Preview — " + report.getName());
            stage.initModality(Modality.APPLICATION_MODAL);
            stage.setScene(new Scene(root));
            stage.show();
        } catch (IOException e) {
            e.printStackTrace();
            showAlert(Alert.AlertType.ERROR, "Preview Error", "Could not open preview.");
        }
    }

    private void handleDeleteReport(Report report) {
        Alert confirm = new Alert(Alert.AlertType.CONFIRMATION);
        confirm.setTitle("Confirm Deletion");
        confirm.setHeaderText("Delete \"" + report.getName() + "\"?");
        confirm.setContentText("This action cannot be undone.");
        if (confirm.showAndWait().orElse(ButtonType.CANCEL) == ButtonType.OK) {
            try {
                service.deleteById(report.getId());
                reportData.remove(report);
                updateToolbarButtons();
            } catch (Exception e) {
                showAlert(Alert.AlertType.ERROR, "Delete Failed", e.getMessage());
            }
        }
    }

    private void updateToolbarButtons() {
        boolean anySelected = reportData.stream().anyMatch(Report::isSelected);
        if (btnDownload  != null) btnDownload.setDisable(!anySelected);
        if (btnExportCsv != null) btnExportCsv.setDisable(reportData.isEmpty());
    }

    private String resolveSortField(String label) {
        if (label == null) return "generated_date_time";

        if (label.contains("Report Name"))    return "name";
        if (label.contains("Generated By"))   return "generated_by";
        if (label.contains("Date Generated")) return "generated_date_time";

        return "generated_date_time";
    }

    private boolean isAscending(String label) {
        if (label == null) return false;

        // "A-Z" and "Oldest" require SQL ASC (true)
        // Note: Using .contains() is safer than .endsWith() because of parentheses
        if (label.contains("A-Z") || label.contains("(Oldest)")) {
            return true;
        }

        // "Z-A" and "Newest" require SQL DESC (false)
        return false;
    }

    private String sanitize(String name) {
        return name == null ? "report" : name.replaceAll("[^a-zA-Z0-9_\\-]", "_");
    }

    private String csv(String value) {
        if (value == null) return "";
        if (value.contains(",") || value.contains("\"") || value.contains("\n"))
            return "\"" + value.replace("\"", "\"\"") + "\"";
        return value;
    }

    private void showAlert(Alert.AlertType type, String title, String message) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}