package com.example.csit228capstone.controller.reports;

import com.example.csit228capstone.model.report.Report;
import com.example.csit228capstone.model.report.ReportData;
import com.example.csit228capstone.service.ReportService;
import com.example.csit228capstone.service.report.ReportExporter;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

import java.io.File;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

/**
 * Controller for ReportPreview.fxml.
 * Shows a TableView preview of the report data and lets the user
 * pick a format and export/download.
 */
public class ReportPreviewController {

    @FXML private Label  lblTitle;
    @FXML private Label  lblMeta;
    @FXML private Label  lblSummary;
    @FXML private TableView<ObservableList<String>> previewTable;
    @FXML private ComboBox<String> cbFormat;
    @FXML private Button btnExport;
    @FXML private Button btnClose;
    @FXML private VBox   rootVBox;

    private final ReportService service = new ReportService();
    private Report      currentReport;
    private ReportData  currentData;

    private static final DateTimeFormatter DT_FMT =
            DateTimeFormatter.ofPattern("MMM dd, yyyy HH:mm");

    // ── Initialization ────────────────────────────────────────────────────────

    @FXML
    public void initialize() {
        // Populate format ComboBox from the service registry
        Map<String, ReportExporter> exporters = service.getExporters();
        cbFormat.setItems(FXCollections.observableArrayList(exporters.keySet()));
        cbFormat.getSelectionModel().selectFirst();
    }

    /**
     * Called by ReportsController before showing this window.
     */
    public void loadReport(Report report) {
        this.currentReport = report;
        this.currentData   = service.buildPreview(report);
        populateUI();
    }

    // ── UI population ─────────────────────────────────────────────────────────

    private void populateUI() {
        // Title & metadata
        lblTitle.setText(currentData.getTitle());

        String meta = "Generated by: " + nvl(currentData.getGeneratedBy());
        if (currentReport.getGeneratedDateTime() != null) {
            meta += "   |   " + currentReport.getGeneratedDateTime().format(DT_FMT);
        }
        lblMeta.setText(meta);

        // Summary
        if (currentData.getSummaryLines() != null && !currentData.getSummaryLines().isEmpty()) {
            lblSummary.setText(String.join("   |   ", currentData.getSummaryLines()));
            lblSummary.setVisible(true);
        } else {
            lblSummary.setVisible(false);
        }

        // Build dynamic TableView columns
        previewTable.getColumns().clear();
        previewTable.getItems().clear();

        List<String> headers = currentData.getHeaders();
        if (headers == null || headers.isEmpty()) return;

        for (int i = 0; i < headers.size(); i++) {
            final int colIdx = i;
            TableColumn<ObservableList<String>, String> col = new TableColumn<>(headers.get(i));
            col.setCellValueFactory(param -> {
                ObservableList<String> row = param.getValue();
                return new javafx.beans.property.SimpleStringProperty(
                        colIdx < row.size() ? nvl(row.get(colIdx)) : "");
            });
            col.setPrefWidth(colIdx == 0 ? 50 : 140);
            previewTable.getColumns().add(col);
        }

        // Populate rows
        if (currentData.getRows() != null) {
            for (List<String> row : currentData.getRows()) {
                previewTable.getItems().add(FXCollections.observableArrayList(row));
            }
        }

        previewTable.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    @FXML
    private void handleExport() {
        String format = cbFormat.getValue();
        if (format == null) {
            showAlert(Alert.AlertType.WARNING, "No Format", "Please select an export format.");
            return;
        }

        ReportExporter exporter = service.getExporters().get(format);
        FileChooser chooser = new FileChooser();
        chooser.setTitle("Save Report As");
        chooser.setInitialFileName(sanitizeFileName(currentData.getTitle()) + "." + exporter.getExtension());
        chooser.getExtensionFilters().add(
                new FileChooser.ExtensionFilter(exporter.getDescription(), "*." + exporter.getExtension()));

        File dest = chooser.showSaveDialog(btnExport.getScene().getWindow());
        if (dest == null) return;  // user cancelled

        try {
            service.export(currentReport, format, dest);
            showAlert(Alert.AlertType.INFORMATION, "Export Successful",
                    "Report saved to:\n" + dest.getAbsolutePath());
        } catch (Exception e) {
            e.printStackTrace();
            showAlert(Alert.AlertType.ERROR, "Export Failed", e.getMessage());
        }
    }

    @FXML
    private void handleClose() {
        ((Stage) btnClose.getScene().getWindow()).close();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private String sanitizeFileName(String name) {
        if (name == null) return "report";
        return name.replaceAll("[^a-zA-Z0-9_\\-]", "_");
    }

    private String nvl(String s) { return s != null ? s : ""; }

    private void showAlert(Alert.AlertType type, String title, String msg) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(msg);
        alert.showAndWait();
    }
}