package com.example.csit228capstone.controller.reports;

import com.example.csit228capstone.model.report.Report;
import com.example.csit228capstone.repository.ReportRepository;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.collections.transformation.FilteredList;
import javafx.collections.transformation.SortedList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.HBox;
import javafx.stage.Modality;
import javafx.stage.Stage;

import java.io.IOException;
import java.util.List;

public class ReportsController {

    @FXML private Button           btnDownload;
    @FXML private CheckBox         selectAllHeader;
    @FXML private TextField        tfSearch;
    @FXML private ComboBox<String> filterType;
    @FXML private ComboBox<String> filterAscOrDesc;

    @FXML private TableView<Report>            reportsTable;
    @FXML private TableColumn<Report, Boolean> colSelect;
    @FXML private TableColumn<Report, String>  colName;
    @FXML private TableColumn<Report, String>  colType;
    @FXML private TableColumn<Report, String>  colGeneratedDateTime;
    @FXML private TableColumn<Report, String>  colGeneratedBy;
    @FXML private TableColumn<Report, Void>    colActions;

    private final ObservableList<Report> reportData   = FXCollections.observableArrayList();
    private final ReportRepository       repository   = new ReportRepository();

    private FilteredList<Report>         filteredData;
    private SortedList<Report>           sortedData;

    @FXML
    public void initialize() {
        setUpTable();

        if (filterAscOrDesc != null) {
            filterAscOrDesc.setItems(FXCollections.observableArrayList(
                    "Generated Date",
                    "Name",
                    "Type",
                    "Generated By"

            ));
            filterAscOrDesc.setValue("Generated Date");
        }

        loadReports();
        setupFilteringAndSorting();
    }

    private void setUpTable() {
        setupSelectColumn();

        colName.setCellValueFactory(new PropertyValueFactory<>("name"));
        colType.setCellValueFactory(new PropertyValueFactory<>("type"));
        colGeneratedDateTime.setCellValueFactory(new PropertyValueFactory<>("formattedDate"));
        colGeneratedBy.setCellValueFactory(new PropertyValueFactory<>("generatedBy"));

        centerColumnText(colName);
        centerColumnText(colType);
        centerColumnText(colGeneratedDateTime);
        centerColumnText(colGeneratedBy);

        setupActionColumn();
    }

    private void setupFilteringAndSorting() {
        filteredData = new FilteredList<>(reportData, p -> true);

        tfSearch.textProperty().addListener((obs, oldVal, newVal) -> applyFilterPredicate());
        if (filterType != null) {
            filterType.valueProperty().addListener((obs, oldVal, newVal) -> applyFilterPredicate());
        }

        sortedData = new SortedList<>(filteredData);

        if (filterAscOrDesc != null) {
            filterAscOrDesc.valueProperty().addListener((obs, oldVal, newVal) -> applySortingComparator());
        }

        applySortingComparator();
        reportsTable.setItems(sortedData);
    }

    private void applyFilterPredicate() {
        String searchText = tfSearch.getText() == null ? "" : tfSearch.getText().toLowerCase().trim();
        String selectedType = filterType != null ? filterType.getValue() : "All";
        if (selectedType == null) selectedType = "All";

        final String typeFilter = selectedType;

        filteredData.setPredicate(report -> {
            if (!typeFilter.equals("All") && report.getType() != null) {
                if (!report.getType().equalsIgnoreCase(typeFilter)) {
                    return false;
                }
            }

            if (searchText.isEmpty()) {
                return true;
            }

            boolean matchesName = report.getName() != null && report.getName().toLowerCase().contains(searchText);
            boolean matchesBy   = report.getGeneratedBy() != null && report.getGeneratedBy().toLowerCase().contains(searchText);
            boolean matchesType = report.getType() != null && report.getType().toLowerCase().contains(searchText);

            return matchesName || matchesBy || matchesType;
        });

        updateDownloadButtonState();
    }

    private void applySortingComparator() {
        String criteria = filterAscOrDesc != null ? filterAscOrDesc.getValue() : "Generated Date";
        if (criteria == null) criteria = "Generated Date";

        switch (criteria) {
            case "Type":
                sortedData.setComparator((r1, r2) -> {
                    if (r1.getType() == null) return -1;
                    if (r2.getType() == null) return 1;
                    return r1.getType().compareToIgnoreCase(r2.getType());
                });
                break;

            case "Generated By":
                sortedData.setComparator((r1, r2) -> {
                    if (r1.getGeneratedBy() == null) return -1;
                    if (r2.getGeneratedBy() == null) return 1;
                    return r1.getGeneratedBy().compareToIgnoreCase(r2.getGeneratedBy());
                });
                break;

            case "Name":
                sortedData.setComparator((r1, r2) -> {
                    if (r1.getName() == null) return -1;
                    if (r2.getName() == null) return 1;
                    return r1.getName().compareToIgnoreCase(r2.getName());
                });
                break;

            case "Generated Date":
            default:
                sortedData.setComparator((r1, r2) -> {
                    if (r1.getGeneratedDateTime() == null) return 1;
                    if (r2.getGeneratedDateTime() == null) return -1;
                    return r2.getGeneratedDateTime().compareTo(r1.getGeneratedDateTime());
                });
                break;

        }
    }

    private void centerColumnText(TableColumn<Report, String> column) {
        column.setCellFactory(col -> new TableCell<>() {
            @Override
            protected void updateItem(String item, boolean empty) {
                super.updateItem(item, empty);
                if (empty || item == null) {
                    setText(null);
                } else {
                    setText(item);
                }
                setStyle("-fx-alignment: CENTER;");
            }
        });
    }

    private void setupSelectColumn() {
        colSelect.setCellValueFactory(new PropertyValueFactory<>("selected"));
        colSelect.setCellFactory(column -> new TableCell<>() {
            private final CheckBox checkBox = new CheckBox();
            {
                checkBox.setOnAction(event -> {
                    Report r = getTableView().getItems().get(getIndex());
                    r.setSelected(checkBox.isSelected());
                    updateDownloadButtonState();
                });
            }
            @Override
            protected void updateItem(Boolean item, boolean empty) {
                super.updateItem(item, empty);
                if (empty) { setGraphic(null); return; }
                Report r = getTableView().getItems().get(getIndex());
                checkBox.setSelected(r.isSelected());
                setGraphic(checkBox);
                setStyle("-fx-alignment: CENTER;");
            }
        });
    }

    private void setupActionColumn() {
        colActions.setCellFactory(param -> new TableCell<>() {
            private final Button btnView   = new Button("View");
            private final Button btnDelete = new Button("Delete");
            private final HBox   container = new HBox(10, btnView, btnDelete);
            {

                btnView.setStyle("""
                    -fx-background-color: #d4a017;
                    -fx-text-fill: white;
                    -fx-font-size: 11px;
                    -fx-padding: 5 12 5 12;
                    -fx-background-radius: 8;
                    -fx-cursor: hand;
                    """);

                btnDelete.setStyle("""
                    -fx-background-color: #c0392b;
                    -fx-text-fill: white;
                    -fx-font-size: 11px;
                    -fx-padding: 5 12 5 12;
                    -fx-background-radius: 8;
                    -fx-cursor: hand;
                    """);

                container.setStyle("-fx-alignment: CENTER;");

                btnView.setOnAction(event -> {
                    Report r = getTableView().getItems().get(getIndex());
                    if (r != null) openPreviewForSaved(r);
                });

                btnDelete.setOnAction(event -> {
                    Report r = getTableView().getItems().get(getIndex());
                    handleDeleteReport(r);
                });
            }
            @Override
            protected void updateItem(Void item, boolean empty) {
                super.updateItem(item, empty);
                setGraphic(empty ? null : container);
                setStyle("-fx-alignment: CENTER;");
            }
        });
    }

    public void loadReports() {
        try {
            List<Report> reports = repository.findAll();
            reportData.setAll(reports);

            if (filterType != null) {
                ObservableList<String> types = FXCollections.observableArrayList("All");
                for (Report r : reports) {
                    if (r.getType() != null && !r.getType().isBlank() && !types.contains(r.getType())) {
                        types.add(r.getType());
                    }
                }
                filterType.setItems(types);
                filterType.setValue("All");
            }
        } catch (Exception e) {
            showAlert(Alert.AlertType.ERROR, "Database Error", "Failed to load reports: " + e.getMessage());
        }
    }

    @FXML
    private void generateReport(ActionEvent event) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/com/example/csit228capstone/report/ReportForm.fxml"));
            Parent root = loader.load();
            ReportFormController ctrl = loader.getController();
            ctrl.setParentController(this);

            Stage stage = new Stage();

            if (reportsTable.getScene() != null) {
                stage.initOwner(reportsTable.getScene().getWindow());
            }
            stage.setTitle("Generate New Report");
            stage.initModality(Modality.APPLICATION_MODAL);
            stage.setScene(new Scene(root));

            stage.setResizable(false);
            stage.setFullScreen(false);

            stage.show();
        } catch (IOException e) {
            e.printStackTrace();
            showAlert(Alert.AlertType.ERROR, "Navigation Error", "Could not load report form.");
        }
    }

    private void openPreviewForSaved(Report report) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/com/example/csit228capstone/report/ReportPreview.fxml"));
            Parent root = loader.load();
            ReportPreviewController ctrl = loader.getController();
            ctrl.loadSavedReport(report);

            Stage stage = new Stage();

            if (reportsTable.getScene() != null) {
                stage.initOwner(reportsTable.getScene().getWindow());
            }

            stage.setResizable(true);
            stage.setFullScreen(false);

            stage.setTitle("Preview — " + report.getName());
            stage.initModality(Modality.APPLICATION_MODAL);
            stage.setScene(new Scene(root));
            stage.setMinWidth(820);
            stage.setMinHeight(700);
            stage.show();
        } catch (IOException e) {
            e.printStackTrace();
            showAlert(Alert.AlertType.ERROR, "Preview Error", "Could not open preview.");
        }
    }

    public void downloadReports(ActionEvent event) {
        List<Report> selected = reportData.stream().filter(Report::isSelected).toList();
        if (selected.isEmpty()) {
            showAlert(Alert.AlertType.WARNING, "Nothing selected", "Please check at least one report.");
            return;
        }
        for (Report r : selected) openPreviewForSaved(r);
    }

    @FXML
    private void handleSelectAll(ActionEvent event) {
        boolean sel = selectAllHeader.isSelected();
        List<Report> targetList = (filteredData != null) ? filteredData : reportData;
        for (Report r : targetList) {
            r.setSelected(sel);
        }
        reportsTable.refresh();
        updateDownloadButtonState();
    }

    private void handleDeleteReport(Report report) {
        Alert confirm = new Alert(Alert.AlertType.CONFIRMATION);

        if (reportsTable.getScene() != null) {
            confirm.initOwner(reportsTable.getScene().getWindow());
        }

        confirm.setTitle("Confirm Deletion");
        confirm.setHeaderText("Delete \"" + report.getName() + "\"?");
        confirm.setContentText("This action cannot be undone.");
        if (confirm.showAndWait().orElse(ButtonType.CANCEL) == ButtonType.OK) {
            try {
                repository.deleteById(report.getId());
                reportData.remove(report);
                updateDownloadButtonState();
            } catch (Exception e) {
                showAlert(Alert.AlertType.ERROR, "Delete Failed", e.getMessage());
            }
        }
    }

    private void updateDownloadButtonState() {
        boolean any = reportData.stream().anyMatch(Report::isSelected);
        if (btnDownload != null) btnDownload.setDisable(!any);
    }

    private void showAlert(Alert.AlertType type, String title, String message) {
        Alert a = new Alert(type);

        if (reportsTable.getScene() != null && reportsTable.getScene().getWindow() != null) {
            a.initOwner(reportsTable.getScene().getWindow());
        }

        a.setTitle(title);
        a.setHeaderText(null);
        a.setContentText(message);
        a.showAndWait();
    }

}